'use client';

import { useEffect, useState, type FormEvent } from 'react';
import styles from './team-modal.module.css';
type Broker = { id: string; name: string; role: 'owner' | 'broker'; active: boolean; created_at: string };
export default function TeamModal({ close, notify }: { close: () => void; notify: (message: string) => void }) {
  const [team, setTeam] = useState<Broker[]>([]); const [limit, setLimit] = useState(5); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; fetch('/api/brokers', { cache: 'no-store' }).then(async (response) => { const result = await response.json() as { data?: Broker[]; brokerLimit?: number; error?: string }; if (!response.ok) throw new Error(result.error || 'Não foi possível carregar a equipe.'); if (active) { setTeam(result.data || []); setLimit(result.brokerLimit || 5); } }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : 'Não foi possível carregar a equipe.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const response = await fetch('/api/brokers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), password: form.get('password') }) }).catch(() => null); const result = await response?.json().catch(() => ({})) as { data?: Broker; error?: string } | undefined; if (!response?.ok || !result?.data) { setError(result?.error || 'Não foi possível cadastrar o corretor.'); setSaving(false); return; } setTeam((current) => [...current, result.data!]); setSaving(false); event.currentTarget.reset(); notify('Corretor cadastrado. Envie a ele o nome da empresa, o nome e a senha.'); }
  const brokers = team.filter((item) => item.role === 'broker' && item.active);
  return <div className="modal-backdrop" role="presentation" onMouseDown={close}><article className={`modal-card ${styles.card}`} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Painel do administrador</p><h2>Corretores</h2></div><button type="button" aria-label="Fechar" onClick={close}>×</button></div><p className={styles.plan}><strong>Plano Basic</strong><span>{brokers.length} de {limit} corretores cadastrados</span></p>{loading ? <p className={styles.empty}>Carregando equipe…</p> : <ul className={styles.list}>{team.map((person) => <li key={person.id}><span>{person.name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()}</span><div><strong>{person.name}</strong><small>{person.role === 'owner' ? 'Administrador' : 'Corretor'}</small></div><em>{person.active ? 'Ativo' : 'Inativo'}</em></li>)}</ul>}<form className={styles.form} onSubmit={create}><h3>Novo corretor</h3><label>Nome completo<input name="name" required minLength={2} maxLength={120} autoComplete="off" placeholder="Ex.: Ana Martins" /></label><label>Senha inicial<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password" placeholder="Mínimo de 12 caracteres" /></label>{error && <p className="access-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={close}>Fechar</button><button className="primary-button" type="submit" disabled={saving || loading || brokers.length >= limit}>{saving ? 'Cadastrando…' : brokers.length >= limit ? 'Limite do Basic atingido' : 'Cadastrar corretor'}</button></div></form></article></div>;
}
