import {
  PrismaClient,
  PropertyStatus,
  PropertyType,
  TransactionType,
} from "@prisma/client";

const prisma = new PrismaClient();

const TENANT_ID = "tenant_demo";
const BROKER_ID = "broker_demo";

type DemoPropertySeed = {
  externalId: string;
  title: string;
  description: string;
  transactionType: TransactionType;
  propertyType: PropertyType;
  price: string;
  condoFee: string | null;
  propertyTax: string | null;
  city: string;
  state: string;
  neighborhood: string;
  address: string;
  latitude: string;
  longitude: string;
  bedrooms: number;
  bathrooms: number;
  parkingSpaces: number;
  areaM2: string;
  furnished: boolean;
  acceptsFinancing: boolean;
  features: string[];
};

const demoProperties: DemoPropertySeed[] = [
  {
    externalId: "DEMO-001",
    title: "[DEMO FICTÍCIO] Apartamento ensolarado na Vila Mariana",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento com planta integrada, varanda e área de lazer simulada.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "745000.00",
    condoFee: "780.00",
    propertyTax: "245.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Vila Mariana",
    address: "Rua Exemplo da Aurora, 101",
    latitude: "-23.5895000",
    longitude: "-46.6341000",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    areaM2: "72.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["varanda", "academia", "salão de festas", "portaria 24h"],
  },
  {
    externalId: "DEMO-002",
    title: "[DEMO FICTÍCIO] Apartamento mobiliado em Pinheiros",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Unidade mobiliada perto de serviços, com coworking e lavanderia coletiva simulados.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "5200.00",
    condoFee: "910.00",
    propertyTax: "310.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Pinheiros",
    address: "Alameda Modelo das Artes, 202",
    latitude: "-23.5665000",
    longitude: "-46.6813000",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    areaM2: "68.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "coworking", "lavanderia", "bicicletário"],
  },
  {
    externalId: "DEMO-003",
    title: "[DEMO FICTÍCIO] Casa com jardim no Alto da Boa Vista",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa ampla com jardim cenográfico, escritório e espaço gourmet.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.HOUSE,
    price: "1850000.00",
    condoFee: null,
    propertyTax: "780.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Alto da Boa Vista",
    address: "Rua Inventada dos Ipês, 303",
    latitude: "-23.6415000",
    longitude: "-46.6945000",
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 3,
    areaM2: "285.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["jardim", "escritório", "espaço gourmet", "suíte master"],
  },
  {
    externalId: "DEMO-004",
    title: "[DEMO FICTÍCIO] Loja térrea no Centro",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Espaço comercial de esquina, com vitrine e depósito ilustrativos.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.COMMERCIAL,
    price: "8900.00",
    condoFee: null,
    propertyTax: "620.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Centro",
    address: "Rua Comercial de Mentirinha, 404",
    latitude: "-23.5477000",
    longitude: "-46.6359000",
    bedrooms: 0,
    bathrooms: 2,
    parkingSpaces: 0,
    areaM2: "140.00",
    furnished: false,
    acceptsFinancing: false,
    features: ["vitrine", "depósito", "esquina", "pé-direito alto"],
  },
  {
    externalId: "DEMO-005",
    title: "[DEMO FICTÍCIO] Terreno residencial em Atibaia",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Lote plano hipotético em via tranquila, pronto para projeto residencial.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.LAND,
    price: "390000.00",
    condoFee: "420.00",
    propertyTax: "115.00",
    city: "Atibaia",
    state: "SP",
    neighborhood: "Jardim dos Pinheiros",
    address: "Estrada Fictícia do Horizonte, lote 5",
    latitude: "-23.1171000",
    longitude: "-46.5563000",
    bedrooms: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    areaM2: "600.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["terreno plano", "condomínio", "portaria", "vista para serra"],
  },
  {
    externalId: "DEMO-006",
    title: "[DEMO FICTÍCIO] Apartamento familiar no Cambuí",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento espaçoso com varanda gourmet e duas vagas simuladas.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "1120000.00",
    condoFee: "1050.00",
    propertyTax: "360.00",
    city: "Campinas",
    state: "SP",
    neighborhood: "Cambuí",
    address: "Rua Cenográfica dos Cafés, 606",
    latitude: "-22.8949000",
    longitude: "-47.0509000",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    areaM2: "118.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["varanda gourmet", "piscina", "brinquedoteca", "duas vagas"],
  },
  {
    externalId: "DEMO-007",
    title: "[DEMO FICTÍCIO] Casa térrea em Barão Geraldo",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa térrea mobiliada, com quintal e ateliê apenas ilustrativos.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.HOUSE,
    price: "4300.00",
    condoFee: null,
    propertyTax: "260.00",
    city: "Campinas",
    state: "SP",
    neighborhood: "Barão Geraldo",
    address: "Rua Imaginária das Jabuticabeiras, 707",
    latitude: "-22.8173000",
    longitude: "-47.0708000",
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    areaM2: "165.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["quintal", "ateliê", "mobiliado", "pet friendly"],
  },
  {
    externalId: "DEMO-008",
    title: "[DEMO FICTÍCIO] Apartamento com vista no Gonzaga",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Unidade de referência com vista lateral para o mar e lazer completo simulado.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "980000.00",
    condoFee: "1250.00",
    propertyTax: "390.00",
    city: "Santos",
    state: "SP",
    neighborhood: "Gonzaga",
    address: "Avenida Exemplo do Atlântico, 808",
    latitude: "-23.9672000",
    longitude: "-46.3321000",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    areaM2: "126.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["vista lateral para o mar", "piscina", "sauna", "varanda"],
  },
  {
    externalId: "DEMO-009",
    title: "[DEMO FICTÍCIO] Apartamento compacto na Ponta da Praia",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento compacto mobiliado com varanda e vaga demarcada fictícias.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "3600.00",
    condoFee: "720.00",
    propertyTax: "210.00",
    city: "Santos",
    state: "SP",
    neighborhood: "Ponta da Praia",
    address: "Rua Ilustrativa das Gaivotas, 909",
    latitude: "-23.9863000",
    longitude: "-46.3058000",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 1,
    areaM2: "48.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "varanda", "vaga demarcada", "ar-condicionado"],
  },
  {
    externalId: "DEMO-010",
    title: "[DEMO FICTÍCIO] Sobrado no Jardim do Mar",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Sobrado com três suítes, churrasqueira e garagem coberta simuladas.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.HOUSE,
    price: "1280000.00",
    condoFee: null,
    propertyTax: "420.00",
    city: "São Bernardo do Campo",
    state: "SP",
    neighborhood: "Jardim do Mar",
    address: "Rua Protótipo das Acácias, 1010",
    latitude: "-23.6919000",
    longitude: "-46.5533000",
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 3,
    areaM2: "224.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["três suítes", "churrasqueira", "garagem coberta", "sala íntima"],
  },
  {
    externalId: "DEMO-011",
    title: "[DEMO FICTÍCIO] Sala comercial no Centro de Santo André",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Conjunto comercial modular com recepção e salas de reunião ilustrativas.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.COMMERCIAL,
    price: "540000.00",
    condoFee: "860.00",
    propertyTax: "180.00",
    city: "Santo André",
    state: "SP",
    neighborhood: "Centro",
    address: "Praça Demonstrativa da Indústria, 111",
    latitude: "-23.6572000",
    longitude: "-46.5333000",
    bedrooms: 0,
    bathrooms: 2,
    parkingSpaces: 2,
    areaM2: "82.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["recepção", "sala de reunião", "ar-condicionado", "duas vagas"],
  },
  {
    externalId: "DEMO-012",
    title: "[DEMO FICTÍCIO] Apartamento novo no Tatuapé",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Unidade nova de catálogo com lazer, varanda e depósito privativo simulados.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "4100.00",
    condoFee: "690.00",
    propertyTax: "195.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Tatuapé",
    address: "Rua Exemplo do Metrô, 1212",
    latitude: "-23.5400000",
    longitude: "-46.5766000",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    areaM2: "65.00",
    furnished: false,
    acceptsFinancing: false,
    features: ["varanda", "depósito", "piscina", "quadra"],
  },
  {
    externalId: "DEMO-013",
    title: "[DEMO FICTÍCIO] Casa em condomínio na Granja Viana",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Residência conceitual com piscina, lareira e área verde privativa.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.HOUSE,
    price: "2350000.00",
    condoFee: "980.00",
    propertyTax: "710.00",
    city: "Cotia",
    state: "SP",
    neighborhood: "Granja Viana",
    address: "Alameda Fictícia dos Cedros, 1313",
    latitude: "-23.6014000",
    longitude: "-46.8339000",
    bedrooms: 4,
    bathrooms: 6,
    parkingSpaces: 4,
    areaM2: "390.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["piscina", "lareira", "área verde", "condomínio fechado"],
  },
  {
    externalId: "DEMO-014",
    title: "[DEMO FICTÍCIO] Lote em condomínio em Itu",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Terreno de esquina hipotético em condomínio com clube ilustrativo.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.LAND,
    price: "610000.00",
    condoFee: "760.00",
    propertyTax: "165.00",
    city: "Itu",
    state: "SP",
    neighborhood: "Jardim Paraíso",
    address: "Alameda Inventada dos Bandeirantes, lote 14",
    latitude: "-23.2649000",
    longitude: "-47.2995000",
    bedrooms: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    areaM2: "1000.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["esquina", "leve aclive", "clube", "segurança 24h"],
  },
  {
    externalId: "DEMO-015",
    title: "[DEMO FICTÍCIO] Apartamento amplo em Perdizes",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento com quatro dormitórios, escritório e varanda gourmet simulados.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "1680000.00",
    condoFee: "1380.00",
    propertyTax: "510.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Perdizes",
    address: "Rua Modelo das Perdizes, 1515",
    latitude: "-23.5359000",
    longitude: "-46.6747000",
    bedrooms: 4,
    bathrooms: 4,
    parkingSpaces: 3,
    areaM2: "172.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["escritório", "varanda gourmet", "depósito", "três vagas"],
  },
  {
    externalId: "DEMO-016",
    title: "[DEMO FICTÍCIO] Studio mobiliado na Bela Vista",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Studio compacto de referência com mobiliário e serviços compartilhados.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "2950.00",
    condoFee: "510.00",
    propertyTax: "105.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Bela Vista",
    address: "Rua Cenográfica dos Teatros, 1616",
    latitude: "-23.5580000",
    longitude: "-46.6457000",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    areaM2: "31.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "coworking", "academia", "lavanderia"],
  },
  {
    externalId: "DEMO-017",
    title: "[DEMO FICTÍCIO] Casa mobiliada no Brooklin",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa urbana mobiliada com escritório e quintal de referência.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.HOUSE,
    price: "9800.00",
    condoFee: null,
    propertyTax: "590.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Brooklin",
    address: "Rua Hipotética das Startups, 1717",
    latitude: "-23.6161000",
    longitude: "-46.6839000",
    bedrooms: 3,
    bathrooms: 4,
    parkingSpaces: 2,
    areaM2: "210.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "escritório", "quintal", "ar-condicionado"],
  },
  {
    externalId: "DEMO-018",
    title: "[DEMO FICTÍCIO] Escritório na Vila Olímpia",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Escritório corporativo de amostra com layout aberto e salas privativas.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.COMMERCIAL,
    price: "14500.00",
    condoFee: "2450.00",
    propertyTax: "890.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Vila Olímpia",
    address: "Avenida Protótipo Digital, 1818",
    latitude: "-23.5959000",
    longitude: "-46.6865000",
    bedrooms: 0,
    bathrooms: 4,
    parkingSpaces: 4,
    areaM2: "235.00",
    furnished: false,
    acceptsFinancing: false,
    features: ["layout aberto", "salas privativas", "gerador", "quatro vagas"],
  },
  {
    externalId: "DEMO-019",
    title: "[DEMO FICTÍCIO] Apartamento com varanda na Água Branca",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Unidade de catálogo com integração entre cozinha, sala e varanda.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "690000.00",
    condoFee: "640.00",
    propertyTax: "175.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "Água Branca",
    address: "Rua Demonstrativa das Fábricas, 1919",
    latitude: "-23.5239000",
    longitude: "-46.6901000",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    areaM2: "64.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["varanda", "cozinha integrada", "piscina", "pet place"],
  },
  {
    externalId: "DEMO-020",
    title: "[DEMO FICTÍCIO] Casa contemporânea no Taquaral",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa conceitual com energia solar, piscina e cozinha gourmet.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.HOUSE,
    price: "1590000.00",
    condoFee: null,
    propertyTax: "480.00",
    city: "Campinas",
    state: "SP",
    neighborhood: "Taquaral",
    address: "Rua Imaginária da Lagoa, 2020",
    latitude: "-22.8756000",
    longitude: "-47.0517000",
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 3,
    areaM2: "275.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["energia solar", "piscina", "cozinha gourmet", "suíte térrea"],
  },
  {
    externalId: "DEMO-021",
    title: "[DEMO FICTÍCIO] Apartamento perto da praia no Boqueirão",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento mobiliado ilustrativo a poucas quadras da praia.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "2800.00",
    condoFee: "590.00",
    propertyTax: "145.00",
    city: "Praia Grande",
    state: "SP",
    neighborhood: "Boqueirão",
    address: "Avenida Fictícia da Orla, 2121",
    latitude: "-24.0084000",
    longitude: "-46.4120000",
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 1,
    areaM2: "58.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "sacada", "vaga", "elevador"],
  },
  {
    externalId: "DEMO-022",
    title: "[DEMO FICTÍCIO] Terreno para projeto em Sorocaba",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Lote residencial hipotético com topografia plana e infraestrutura simulada.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.LAND,
    price: "285000.00",
    condoFee: "350.00",
    propertyTax: "90.00",
    city: "Sorocaba",
    state: "SP",
    neighborhood: "Alto da Boa Vista",
    address: "Rua Modelo dos Tropeiros, lote 22",
    latitude: "-23.4679000",
    longitude: "-47.4292000",
    bedrooms: 0,
    bathrooms: 0,
    parkingSpaces: 0,
    areaM2: "360.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["plano", "condomínio", "rede de água", "rede elétrica"],
  },
  {
    externalId: "DEMO-023",
    title: "[DEMO FICTÍCIO] Loja comercial em Alphaville",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Loja de amostra em corredor comercial, com mezanino e estacionamento.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.COMMERCIAL,
    price: "1350000.00",
    condoFee: "1280.00",
    propertyTax: "540.00",
    city: "Barueri",
    state: "SP",
    neighborhood: "Alphaville",
    address: "Alameda Exemplo dos Negócios, 2323",
    latitude: "-23.4957000",
    longitude: "-46.8488000",
    bedrooms: 0,
    bathrooms: 3,
    parkingSpaces: 5,
    areaM2: "190.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["mezanino", "vitrine", "estacionamento", "copa"],
  },
  {
    externalId: "DEMO-024",
    title: "[DEMO FICTÍCIO] Apartamento mobiliado em Alphaville",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento executivo mobiliado com serviços e lazer ilustrativos.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.APARTMENT,
    price: "6400.00",
    condoFee: "1180.00",
    propertyTax: "330.00",
    city: "Barueri",
    state: "SP",
    neighborhood: "Alphaville",
    address: "Alameda Cenográfica dos Lagos, 2424",
    latitude: "-23.4931000",
    longitude: "-46.8508000",
    bedrooms: 2,
    bathrooms: 3,
    parkingSpaces: 2,
    areaM2: "92.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "arrumação", "piscina", "academia"],
  },
  {
    externalId: "DEMO-025",
    title: "[DEMO FICTÍCIO] Casa com vista para a serra em Mairiporã",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa de campo conceitual com deck, lareira e vista panorâmica simulada.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.HOUSE,
    price: "1380000.00",
    condoFee: "620.00",
    propertyTax: "350.00",
    city: "Mairiporã",
    state: "SP",
    neighborhood: "Serra da Cantareira",
    address: "Estrada Imaginária da Neblina, 2525",
    latitude: "-23.3509000",
    longitude: "-46.5885000",
    bedrooms: 4,
    bathrooms: 4,
    parkingSpaces: 4,
    areaM2: "310.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["deck", "lareira", "vista panorâmica", "pomar"],
  },
  {
    externalId: "DEMO-026",
    title: "[DEMO FICTÍCIO] Loft de referência na República",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Loft cenográfico de uso residencial, com pé-direito alto e mezanino.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.OTHER,
    price: "3350.00",
    condoFee: "580.00",
    propertyTax: "120.00",
    city: "São Paulo",
    state: "SP",
    neighborhood: "República",
    address: "Rua Protótipo dos Modernistas, 2626",
    latitude: "-23.5448000",
    longitude: "-46.6433000",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpaces: 0,
    areaM2: "44.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["loft", "mezanino", "pé-direito alto", "mobiliado"],
  },
  {
    externalId: "DEMO-027",
    title: "[DEMO FICTÍCIO] Apartamento no Jardim Aquarius",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Apartamento familiar de amostra com varanda gourmet e clube completo.",
    transactionType: TransactionType.BUY,
    propertyType: PropertyType.APARTMENT,
    price: "920000.00",
    condoFee: "830.00",
    propertyTax: "270.00",
    city: "São José dos Campos",
    state: "SP",
    neighborhood: "Jardim Aquarius",
    address: "Rua Fictícia das Constelações, 2727",
    latitude: "-23.2157000",
    longitude: "-45.9059000",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpaces: 2,
    areaM2: "108.00",
    furnished: false,
    acceptsFinancing: true,
    features: ["varanda gourmet", "clube", "quadra", "duas vagas"],
  },
  {
    externalId: "DEMO-028",
    title: "[DEMO FICTÍCIO] Casa em condomínio na Nova Aliança",
    description:
      "ANÚNCIO FICTÍCIO PARA DEMONSTRAÇÃO. Casa mobiliada de referência com piscina e espaço gourmet.",
    transactionType: TransactionType.RENT,
    propertyType: PropertyType.HOUSE,
    price: "7200.00",
    condoFee: "690.00",
    propertyTax: "410.00",
    city: "Ribeirão Preto",
    state: "SP",
    neighborhood: "Nova Aliança",
    address: "Alameda Demonstrativa do Café, 2828",
    latitude: "-21.2135000",
    longitude: "-47.8214000",
    bedrooms: 4,
    bathrooms: 5,
    parkingSpaces: 3,
    areaM2: "245.00",
    furnished: true,
    acceptsFinancing: false,
    features: ["mobiliado", "piscina", "espaço gourmet", "condomínio"],
  },
];

async function main(): Promise<void> {
  await prisma.tenant.upsert({
    where: { id: TENANT_ID },
    update: {
      name: "Imobiliária Horizonte Demo (Fictícia)",
    },
    create: {
      id: TENANT_ID,
      name: "Imobiliária Horizonte Demo (Fictícia)",
    },
  });

  await prisma.broker.upsert({
    where: { id: BROKER_ID },
    update: {
      tenantId: TENANT_ID,
      name: "Marina Demo (Corretora Fictícia)",
      email: "corretora.demo@example.invalid",
      phone: "+5511000000000",
      active: true,
    },
    create: {
      id: BROKER_ID,
      tenantId: TENANT_ID,
      name: "Marina Demo (Corretora Fictícia)",
      email: "corretora.demo@example.invalid",
      phone: "+5511000000000",
      active: true,
    },
  });

  await prisma.$transaction(
    demoProperties.map((property) => {
      const imageBaseUrl = `https://images.example.invalid/realestate-demo/${property.externalId.toLowerCase()}`;
      const data = {
        ...property,
        tenantId: TENANT_ID,
        brokerId: BROKER_ID,
        status: PropertyStatus.ACTIVE,
        available: true,
        imageUrls: [`${imageBaseUrl}-1.jpg`, `${imageBaseUrl}-2.jpg`],
        propertyUrl: `https://imoveis.example.invalid/demo/${property.externalId.toLowerCase()}`,
      };

      return prisma.property.upsert({
        where: {
          tenantId_externalId: {
            tenantId: TENANT_ID,
            externalId: property.externalId,
          },
        },
        update: data,
        create: data,
      });
    }),
  );

  console.info(
    `Seed concluído: tenant ${TENANT_ID}, corretor ${BROKER_ID} e ${demoProperties.length} imóveis fictícios.`,
  );
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error: unknown) => {
    console.error("Falha ao executar o seed do ambiente de demonstração:", error);
    await prisma.$disconnect();
    process.exit(1);
  });
