/** Shared form contract. Values are validated again by the server-side engine. */
export type Kind = 'people' | 'leads' | 'cases' | 'tasks' | 'proposals' | 'properties' | 'condominiums' | 'neighborhoods' | 'keys' | 'goals' | 'notes' | 'links' | 'notices' | 'messages' | 'content' | 'channels' | 'teams' | 'followups' | 'captureGoals' | 'shifts';
export type Field = { key: string; label: string; type?: 'text' | 'textarea' | 'number' | 'date' | 'datetime-local' | 'select' | 'email' | 'url'; required?: boolean; options?: string[]; ref?: Kind | 'members'; min?: number };
export type ModuleDefinition = { title: string; singular: string; group: string; fields: Field[]; admin?: boolean; description?: string };
const field = (key: string, label: string, more: Partial<Field> = {}): Field => ({ key, label, ...more });
const name = field('name', 'Nome', { required: true });
const notes = field('notes', 'Observações', { type: 'textarea' });
const assignee = field('assignedTo', 'Responsável', { ref: 'members', required: true });
const purpose = field('purpose', 'Finalidade', { type: 'select', options: ['Venda', 'Aluguel'], required: true });
const person = field('personId', 'Pessoa / cliente', { ref: 'people', required: true });
const caseRef = field('caseId', 'Atendimento', { ref: 'cases', required: true });
const property = field('propertyId', 'Imóvel', { ref: 'properties' });
export const NEGOTIATION_STAGES = ['Lead', 'Atendimento', 'Agendamento', 'Visita', 'Proposta', 'Negociado'];
export const CAPTURE_STAGES = ['Lead', 'Avaliação', 'Captado'];
export const MODULES: Record<Kind, ModuleDefinition> = {
  people: { title: 'Pessoas', singular: 'Pessoa', group: 'Cadastros', fields: [name, field('personType', 'Tipo', {type:'select',options:['Pessoa física','Pessoa jurídica'],required:true}), field('category','Categoria',{type:'select',options:['Cliente','Proprietário','Corretor','Cliente e proprietário'],required:true}), field('phone','Telefone'), field('email','Email',{type:'email'}), field('address','Endereço'), assignee, notes] },
  leads: { title:'Leads', singular:'Lead', group:'CRM', fields:[name,person,assignee,field('source','Origem',{required:true}),purpose,property,field('temperature','Temperatura',{type:'select',options:['Frio','Morno','Quente'],required:true}),field('propertyType','Tipo de imóvel'),field('region','Região'),field('budgetMin','Orçamento mínimo',{type:'number',min:0}),field('budgetMax','Orçamento máximo',{type:'number',min:0}),field('features','Características desejadas'),field('status','Triagem',{type:'select',options:['Pendente','Em atendimento','Descartado'],required:true}),notes] },
  cases: { title:'Atendimentos', singular:'Atendimento', group:'CRM', fields:[name,person,field('leadId','Lead de origem',{ref:'leads'}),field('source','Origem',{required:true}),assignee,purpose,field('journey','Jornada',{type:'select',options:['Negociação','Captação'],required:true}),field('stage','Etapa',{type:'select',options:[...NEGOTIATION_STAGES,'Avaliação','Captado'],required:true}),field('status','Situação',{type:'select',options:['Aberto','Pausado','Ganho','Perdido'],required:true}),property,field('nextActivityAt','Próxima atividade',{type:'datetime-local'}),field('reason','Motivo da pausa / encerramento'),notes] },
  tasks: { title:'Agenda e tarefas', singular:'Atividade', group:'CRM', fields:[name,caseRef,assignee,field('type','Tipo',{type:'select',options:['Tarefa','Visita','Compromisso'],required:true}),property,field('dueAt','Data e horário',{type:'datetime-local',required:true}),field('priority','Prioridade',{type:'select',options:['Normal','Alta'],required:true}),field('status','Situação',{type:'select',options:['Pendente','Confirmada','Realizada','Ausência','Cancelada'],required:true}),field('reason','Motivo / feedback'),notes] },
  proposals: { title:'Propostas',singular:'Proposta',group:'CRM',fields:[name,caseRef,{...property,required:true},field('amount','Valor proposto (R$)',{type:'number',min:0.01,required:true}),field('conditions','Condições',{type:'textarea',required:true}),field('expiresAt','Validade',{type:'date',required:true}),field('status','Situação',{type:'select',options:['Rascunho','Enviada','Em negociação','Aceita','Recusada','Expirada'],required:true}),field('reason','Motivo da recusa / resultado')] },
  properties: { title:'Imóveis',singular:'Imóvel',group:'Imóveis',fields:[name,field('code','Código',{required:true}),purpose,field('price','Preço (R$)',{type:'number',min:0,required:true}),field('status','Situação',{type:'select',options:['Disponível','Reservado','Vendido','Alugado','Arquivado'],required:true}),field('ownerId','Proprietário',{ref:'people'}),assignee,field('condominiumId','Condomínio',{ref:'condominiums'}),field('neighborhoodId','Bairro cadastrado',{ref:'neighborhoods'}),field('district','Bairro do imóvel'),field('address','Endereço'),field('city','Cidade'),field('propertyType','Tipo de imóvel'),field('bedrooms','Quartos',{type:'number',min:0}),field('parkingSpaces','Vagas',{type:'number',min:0}),field('area','Área (m²)',{type:'number',min:0}),field('description','Descrição',{type:'textarea'}),field('photoUrl','URL de foto',{type:'url'}),field('publicUrl','Link de divulgação',{type:'url'}),notes] },
  condominiums: { title:'Condomínios',singular:'Condomínio',group:'Imóveis',fields:[name,field('address','Endereço'),field('city','Cidade',{required:true}),field('features','Características / lazer',{type:'textarea'}),notes] },
  neighborhoods: { title:'Bairros',singular:'Bairro',group:'Imóveis',fields:[name,field('city','Cidade',{required:true}),field('aliases','Apelidos (separados por vírgula)'),notes] },
  keys: { title:'Empréstimo de chaves',singular:'Retirada de chave',group:'Imóveis',fields:[name,{...property,required:true},field('keyCode','Identificação da chave',{required:true}),assignee,field('borrower','Retirada por',{required:true}),field('purpose','Finalidade da retirada',{required:true}),field('dueAt','Previsão de devolução',{type:'datetime-local',required:true}),field('status','Situação',{type:'select',options:['Retirada','Devolvida'],required:true}),notes] },
  goals: { title:'Metas',singular:'Meta',group:'Gestão',admin:true,description:'Metas são informadas manualmente; resultados são calculados a partir das propostas aceitas.',fields:[name,assignee,field('month','Mês (AAAA-MM)',{required:true}),purpose,field('amount','Meta de valor (R$)',{type:'number',min:0,required:true}),notes] },
  teams: { title:'Equipes',singular:'Equipe',group:'Gestão',admin:true,description:'Cadastro de equipes. A distribuição automática permanece desligada; nenhum atendimento existente é transferido.',fields:[name,field('leaderId','Líder',{ref:'members',required:true}),notes] },
  notes: { title:'Minhas notas',singular:'Nota',group:'Ferramentas',fields:[name,field('text','Conteúdo',{type:'textarea',required:true})] },
  links: { title:'Links úteis',singular:'Link',group:'Ferramentas',fields:[name,field('url','Endereço',{type:'url',required:true}),notes] },
  notices: { title:'Mural',singular:'Recado',group:'Ferramentas',admin:true,fields:[name,field('text','Mensagem interna',{type:'textarea',required:true})] },
  messages: { title:'Comunicação interna',singular:'Mensagem interna',group:'Ferramentas',description:'Recados para a equipe, separados das conversas com clientes. Não dispara WhatsApp ou email.',fields:[name,field('recipientId','Destinatário',{ref:'members',required:true}),field('text','Mensagem',{type:'textarea',required:true})] },
  content: { title:'Conteúdo e banners',singular:'Rascunho',group:'Site e divulgação',admin:true,description:'Editor de rascunhos. Não modifica o site público. Publicação exige integração e aprovação em uma etapa posterior.',fields:[name,field('type','Tipo',{type:'select',options:['Página','Banner desktop','Banner mobile'],required:true}),field('text','Conteúdo',{type:'textarea'}),field('imageUrl','URL da imagem',{type:'url'}),field('url','Link de destino',{type:'url'})] },
  channels: { title:'Portais e canais',singular:'Canal',group:'Site e divulgação',admin:true,description:'Inventário de canais e dependências. Não há envio ou conexão automática com portais nesta entrega.',fields:[name,field('url','Endereço do portal',{type:'url'}),field('dependency','Contrato / integração pendente',{type:'textarea',required:true})] },
  followups: { title:'Cobranças e retornos',singular:'Cobrança',group:'Gestão',description:'O gestor define a pendência e o prazo; o corretor responde e o gestor confere a conclusão. Não envia mensagens ao cliente.',fields:[name,assignee,field('caseId','Atendimento relacionado',{ref:'cases'}),field('dueAt','Prazo de retorno',{type:'datetime-local',required:true}),field('priority','Prioridade',{type:'select',options:['Normal','Alta'],required:true}),field('status','Situação',{type:'select',options:['Pendente','Em andamento','Respondida','Concluída','Cancelada'],required:true}),field('request','O que precisa ser feito',{type:'textarea',required:true}),field('response','Resposta do corretor',{type:'textarea'}),field('review','Conferência do gestor',{type:'textarea'})] },
  captureGoals: { title:'Metas de captação',singular:'Meta de captação',group:'Gestão',description:'Conta os imóveis cadastrados no mês, vinculados ao responsável e à finalidade. Importações usam a data de cadastro preservada.',fields:[name,assignee,field('month','Mês (AAAA-MM)',{required:true}),purpose,field('target','Meta de imóveis',{type:'number',min:1,required:true}),notes] },
  shifts: { title:'Plantões',singular:'Plantão',group:'Gestão',description:'Agenda de plantões usada nas recomendações de distribuição. Não transfere automaticamente a carteira.',fields:[name,assignee,field('startsAt','Início',{type:'datetime-local',required:true}),field('endsAt','Fim',{type:'datetime-local',required:true}),field('purpose','Finalidade',{type:'select',options:['Venda','Aluguel','Ambos'],required:true}),field('status','Situação',{type:'select',options:['Ativo','Cancelado'],required:true}),notes] },
};

// Optional qualification fields never discard an incomplete intake. Completeness
// and configurable progression gates are derived separately by the domain engine.
MODULES.people.fields.push(field('preferredChannel','Canal preferido',{type:'select',options:['WhatsApp','Telefone','Email']}),field('contactPeriod','Melhor horário para contato'));
MODULES.leads.fields.push(field('city','Cidade de interesse'),field('bedrooms','Quartos desejados',{type:'number',min:0}),field('parkingSpaces','Vagas desejadas',{type:'number',min:0}),field('purchaseTimeline','Prazo para decidir'),field('financing','Forma de pagamento',{type:'select',options:['À vista','Financiamento','A definir']}),field('qualificationNotes','Detalhes da qualificação',{type:'textarea'}));
MODULES.properties.fields.push(field('bathrooms','Banheiros',{type:'number',min:0}),field('condoFee','Condomínio (R$)',{type:'number',min:0}),field('iptu','IPTU anual (R$)',{type:'number',min:0}),field('features','Comodidades',{type:'textarea'}),field('documentation','Situação documental',{type:'select',options:['A conferir','Regular','Com pendências']}));
