export const chapters = [
  { id: 'overview', label: 'Visão geral', title: 'A operação inteira, em uma visão.', summary: 'O gestor acompanha o trabalho da imobiliária sem procurar informações em várias conversas.', steps: ['Escolha o mês para consultar os resultados.', 'Compare o desempenho da equipe com as metas.', 'Registre os negócios fechados para atualizar os indicadores.'], benefit: 'Mais clareza para decidir onde a equipe precisa de atenção.' },
  { id: 'goals', label: 'Metas', title: 'Todos sabem aonde querem chegar.', summary: 'Defina os objetivos da imobiliária e de cada corretor para o mês.', steps: ['Escolha o mês de referência.', 'Estabeleça a meta da empresa e as metas individuais.', 'Acompanhe o avanço conforme os negócios são registrados.'], benefit: 'O planejamento fica visível para acompanhar o progresso.' },
  { id: 'conversations', label: 'Conversas', title: 'O corretor começa com contexto.', summary: 'O sistema ajuda no início do atendimento pelo WhatsApp. A equipe continua a conversa e conduz a negociação.', steps: ['Selecione o cliente para ler a conversa.', 'Consulte o que ele procura, seu orçamento e o corretor responsável.', 'Continue o atendimento no campo de mensagem ou agende uma visita.'], benefit: 'Menos perguntas repetidas. Mais tempo para conversar com o cliente.' },
  { id: 'leads', label: 'Leads', title: 'Cada interessado tem seu lugar.', summary: 'Aqui ficam os perfis dos interessados, chamados de leads no painel.', steps: ['Encontre o cliente pela busca ou pelos filtros.', 'Confira objetivo, tipo de imóvel, região e investimento.', 'Acompanhe a etapa do atendimento e quem está responsável.'], benefit: 'Informações organizadas para dar continuidade ao atendimento.' },
  { id: 'opportunities', label: 'Oportunidades', title: 'Encontre o imóvel que combina.', summary: 'O painel aproxima os imóveis cadastrados dos interesses de cada cliente.', steps: ['Confira as combinações de objetivo, tipo, região e orçamento.', 'Abra o cliente e o imóvel para revisar os detalhes.', 'Prepare a mensagem e registre o contato depois de realizá-lo.'], benefit: 'A equipe decide quando retomar o contato. Nenhuma venda é garantida pelo match.' },
  { id: 'properties', label: 'Imóveis', title: 'Seu portfólio organizado.', summary: 'Mantenha as informações dos imóveis em um lugar acessível à equipe.', steps: ['Consulte e filtre os imóveis cadastrados.', 'Abra um imóvel para ver seus detalhes.', 'Mantenha valores e disponibilidade atualizados; vincule o imóvel ao registrar uma venda.'], benefit: 'O corretor consulta o portfólio antes de apresentar uma opção ao cliente.' },
  { id: 'agenda', label: 'Agenda', title: 'A próxima visita, bem combinada.', summary: 'Organize os compromissos e saiba quem vai acompanhar cada cliente.', steps: ['Consulte as visitas na agenda.', 'Ao agendar, informe cliente, imóvel, data e corretor.', 'Acompanhe as confirmações e atualize a situação da visita.'], benefit: 'Compromissos e responsáveis ficam claros para a equipe.' },
  { id: 'imports', label: 'Importar clientes', title: 'Aproveite os contatos que já tem.', summary: 'Traga uma planilha de clientes antigos para organizar sua carteira na ImobFlow.', steps: ['Prepare uma planilha CSV seguindo o modelo da tela.', 'Selecione o arquivo e confira a prévia dos dados.', 'Revise os avisos antes de confirmar a importação.'], benefit: 'Importa os dados da planilha, não o histórico antigo do WhatsApp. Não envia mensagens automaticamente.' },
  { id: 'integrations', label: 'Integrações', title: 'O WhatsApp da sua imobiliária.', summary: 'Esta área reúne a configuração do número usado no atendimento.', steps: ['Faça a configuração do WhatsApp com acompanhamento da ImobFlow.', 'Confira os dados da conexão da empresa.', 'Valide o envio e o recebimento antes de iniciar os atendimentos.'], benefit: 'Nesta apresentação, nenhuma conta real é conectada e nenhuma mensagem é enviada.' },
  { id: 'team', label: 'Corretores', title: 'Cada atendimento, com um responsável.', summary: 'O administrador organiza os acessos da equipe à imobiliária.', steps: ['Abra Corretores para consultar a equipe.', 'Cadastre os profissionais e seus dados de acesso.', 'Mantenha os acessos atualizados conforme a equipe mudar.'], benefit: 'A equipe trabalha no mesmo ambiente, com responsabilidades definidas.' },
] as const;

export type ChapterId = typeof chapters[number]['id'];
export type Copy = { title: string; summary: string; steps: string[]; benefit: string };
export const storageKey = 'imobflow.presentation.copy.v1';
export function isChapter(value: unknown): value is ChapterId { return chapters.some(chapter => chapter.id === value); }
export function cleanCopies(value: unknown): Partial<Record<ChapterId, Copy>> {
  if (!value || typeof value !== 'object') return {};
  const result: Partial<Record<ChapterId, Copy>> = {};
  for (const { id } of chapters) {
    const item = (value as Record<string, unknown>)[id] as Copy | undefined;
    if (item && typeof item.title === 'string' && item.title.length <= 120 && typeof item.summary === 'string' && item.summary.length <= 350 && typeof item.benefit === 'string' && item.benefit.length <= 350 && Array.isArray(item.steps) && item.steps.length === 3 && item.steps.every(step => typeof step === 'string' && step.length <= 220)) result[id] = item;
  }
  return result;
}
